### ISSUE TITLE
Complete CRUD on transactions

### ISSUE THREAD

**Issue by Mobashir-Monim** [Eveneer/evengoams-backend#3]
- [ ] Create
- [ ] Update
- [ ] Read
- [ ] Trash

Updates records the previous transaction ID as a parent.

**Comment by Mahir12746** [comment]
No more methods required

**Comment by Mobashir-Monim** [comment]
- `UpdateTransaction` has to be changed to be similar to the `CreateTransaction` action
- Ensure tags sync on update
- Read and search actions are required for transactions
- When trashing/restoring the transaction, the balance of respective accounts will also have to be updated

**Comment by Mobashir-Monim** [comment]
Also when restoring a transaction.
