### ISSUE TITLE
Complete CRUD on vendors

### ISSUE THREAD

**Issue by Mobashir-Monim** [Eveneer/evengoams-backend#5]
- [ ] Create
- [ ] Update
- [ ] Read
- [ ] Trash

**Comment by Mahir12746** [comment]
No more methods required

**Comment by Mobashir-Monim** [comment]
The `UpdateVendor` action needs to be updated so that if the tags on the vendor changes, then the attached tags are also updated. The validation rules for it will have to be updated as well.

**Comment by Mobashir-Monim** [comment]
Read and search actions are required for vendors.
