### ISSUE TITLE
Complete CRUD on tags

### ISSUE THREAD

**Issue by Mobashir-Monim** [Eveneer/evengoams-backend#7]
- [ ] Create
- [ ] Update
- [ ] Read
- [ ] Trash

On create check if existing keys exists on model

**Comment by Mahir12746** [comment]
No more functions required and whether tags exists is already being checked.

**Comment by Mobashir-Monim** [comment]
@Mahir12746, there are unused dependencies not used in some of the actions which needs to be removed. also, the `prepareForValidation` methods are not needed.

Also, look into this: https://www.laravelactions.com/2.x/as-controller.html#routes

See if we can define the api routes directly in the actions.

**Comment by Mobashir-Monim** [comment]
You will also need to update the `UpdateTag` action.

**Comment by Mobashir-Monim** [comment]
Read and search actions are required for tags.
